### ISSUE TITLE
Permissions Bug after cloning the repo and running it

### ISSUE THREAD

**Issue by Youssef-Alaa** [PegaSysEng/besu-sample-networks#82] opened 2020-06-22 19:29 UTC
Hey PegaSys team,
I tried cloning the latest repo here and `./run.sh` on Ubuntu 18.04 LTS, as I have been doing for a lot of time now for my development process.

Expected behavior:   
download images and run containers for peers and services ... etc.

BUT had the following error: 
```
Step 4/6 : RUN (apt-get update && apt-get install dos2unix || apk add --update dos2unix) &&     rm -rf /var/cache/apt/* && rm -rf /var/cache/apk/*  
 ---> Running in 0ce73a4b8e38  
Reading package lists...  
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)  
/bin/sh: 1: apk: not found  
ERROR: Service 'bootnode' failed to build: The command '/bin/sh -c (apt-get update && apt-get install dos2unix || apk add --update dos2unix) &&     rm -rf /var/cache/apt/* && rm -rf /var/cache/apk/*' returned a non-zero code: 127  
Creating network "besu-sample-networks_default" with the default driver  
Creating volume "besu-sample-networks_public-keys" with default driver  
Creating volume "besu-sample-networks_prometheus" with default driver  
Creating volume "besu-sample-networks_grafana" with default driver  
Building bootnode  
Step 1/6 : ARG BESU_VERSION=latest  
Step 2/6 : FROM hyperledger/besu:$BESU_VERSION  
 ---> adddaa4fc688  
Step 3/6 : COPY *_start.sh /opt/besu/  
 ---> Using cache  
 ---> 4b8ba5597863  
Step 4/6 : RUN (apt-get update && apt-get install dos2unix || apk add --update dos2unix) &&     rm -rf /var/cache/apt/* && rm -rf /var/cache/apk/*  
 ---> Running in 48d071029f00  
Reading package lists...  
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)  
/bin/sh: 1: apk: not found  
ERROR: Service 'bootnode' failed to build: The command '/bin/sh -c (apt-get update && apt-get install dos2unix || apk add --update dos2unix) &&     rm -rf /var/cache/apt/* && rm -rf /var/cache/apk/*' returned a non-zero code: 127
```

**Comment by Youssef-Alaa** [comment] 2020-06-22 19:59
I found a simple solution by giving the docker commands root privilege. 
I have submitted a pull request ( number #83 ) with the change.

**Comment by joshuafernandes** [comment] 2020-06-23 02:30
Hi @Youssef-Alaa  Thank you for that. 

#84 should sort that out, we're moving towards security best practices and now make a `besu` user:group for the container. This change was caused by the upcoming breaking changes in v 1.5.0 

Cheers

**Closed by joshuafernandes** 2020-06-23 02:30 UTC
